+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
Python 3.11.6
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Feb 15 13:44:47 2025 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL iSulad
+ pkgs=iSulad
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs iSulad --node 1 --tempfile ''
Sat Feb 15 13:44:55 2025 - INFO  - pkgs:(iSulad) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ cp /etc/isulad/daemon.json /etc/isulad/daemon.json.bak
cp: cannot stat '/etc/isulad/daemon.json': No such file or directory
+ '[' riscv64 == riscv64 ']'
+ sed -i '/registry-mirrors/a\"https:\/\/docker.io\"' /etc/isulad/daemon.json
sed: can't read /etc/isulad/daemon.json: No such file or directory
+ systemctl restart isulad.service
Job for isulad.service failed because the control process exited with error code.
See "systemctl status isulad.service" and "journalctl -xeu isulad.service" for details.
+ isula pull busybox
Image "busybox" pulling
Can not connect with server.Is the iSulad daemon running on the host?
+ isula create -it busybox
Can not connect with server.Is the iSulad daemon running on the host?
++ isula ps -a
++ grep -vi NAMES
++ awk '{print $NF}'
Can not connect with server.Is the iSulad daemon running on the host?
+ container_id=
+ isula start ''
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Feb 15 13:44:57 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Feb 15 13:44:57 2025 - INFO  - Start to run test.
+ isula exec -it '' /bin/sh -c 'ls / | grep bin'
+ CHECK_RESULT 1 0 0 'There is no such file or directory'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='There is no such file or directory'
+ exit_mode=0
+ '[' -z '1 0 0 There is no such file or directory' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'There is no such file or directory'
+ LOG_ERROR 'There is no such file or directory'
+ message='There is no such file or directory'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is no such file or directory'
Sat Feb 15 13:44:58 2025 - ERROR - There is no such file or directory
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container05.sh line 42'
+ message='oe_test_iSulad_container05.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container05.sh line 42'
Sat Feb 15 13:44:58 2025 - ERROR - oe_test_iSulad_container05.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ isula exec -it '' /bin/sh -c 'touch /tmp/test.txt'
+ isula exec -it '' /bin/sh -c 'ls /tmp/test.txt'
+ CHECK_RESULT 1 0 0 'There is no such file or directory'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='There is no such file or directory'
+ exit_mode=0
+ '[' -z '1 0 0 There is no such file or directory' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'There is no such file or directory'
+ LOG_ERROR 'There is no such file or directory'
+ message='There is no such file or directory'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is no such file or directory'
Sat Feb 15 13:44:59 2025 - ERROR - There is no such file or directory
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container05.sh line 45'
+ message='oe_test_iSulad_container05.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container05.sh line 45'
Sat Feb 15 13:44:59 2025 - ERROR - oe_test_iSulad_container05.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ isula exec -it '' /bin/sh -c exit
+ CHECK_RESULT 1 0 0 'Failed to exit container'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to exit container'
+ exit_mode=0
+ '[' -z '1 0 0 Failed to exit container' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to exit container'
+ LOG_ERROR 'Failed to exit container'
+ message='Failed to exit container'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to exit container'
Sat Feb 15 13:45:00 2025 - ERROR - Failed to exit container
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container05.sh line 47'
+ message='oe_test_iSulad_container05.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container05.sh line 47'
Sat Feb 15 13:45:00 2025 - ERROR - oe_test_iSulad_container05.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Feb 15 13:45:01 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Feb 15 13:45:01 2025 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Feb 15 13:45:01 2025 - INFO  - Start to restore the test environment.
+ isula ps -a
+ grep -vi NAMES
+ awk '{print $NF}'
+ xargs -I '{}' isula stop '{}'
Can not connect with server.Is the iSulad daemon running on the host?
+ isula ps -a
+ grep -vi NAMES
+ awk '{print $NF}'
+ xargs -I '{}' isula rm -f '{}'
Can not connect with server.Is the iSulad daemon running on the host?
+ isula rmi busybox
Can not connect with server.Is the iSulad daemon running on the host?
+ mv -f /etc/isulad/daemon.json.bak /etc/isulad/daemon.json
mv: cannot stat '/etc/isulad/daemon.json.bak': No such file or directory
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Sat Feb 15 13:45:02 2025 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Feb 15 13:45:03 2025 - INFO  - End to restore the test environment.
