+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
Python 3.11.6
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Feb 15 14:13:38 2025 - INFO  - Start to prepare the test environment.
+ swapoff /dev/dm-1
swapoff: /dev/dm-1: swapoff failed: No such file or directory
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Feb 15 14:13:38 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Feb 15 14:13:39 2025 - INFO  - Start to run test.
++ free -lh
++ grep -i swap
++ awk '{print $2}'
++ awk -FG '{print $1}'
+ default_swap=0B
+ swapoff /dev/dm-1
swapoff: /dev/dm-1: swapoff failed: No such file or directory
++ free -lh
++ grep -i swap
++ awk '{print $2}'
++ awk -FB '{print $1}'
+ swap1=0
+ CHECK_RESULT 0 0 0 'Uninstall Failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Uninstall Failed'
+ exit_mode=0
+ '[' -z '0 0 0 Uninstall Failed' ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ lvreduce -L -1G -f '/dev/openeuler*/swap'
oe_test_swap_compress.sh: line 33: lvreduce: command not found
+ mkswap '/dev/openeuler*/swap'
mkswap: cannot open /dev/openeuler*/swap: No such file or directory
+ CHECK_RESULT 1 0 0 'Erase failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Erase failed'
+ exit_mode=0
+ '[' -z '1 0 0 Erase failed' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Erase failed'
+ LOG_ERROR 'Erase failed'
+ message='Erase failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Erase failed'
Sat Feb 15 14:13:39 2025 - ERROR - Erase failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_swap_compress.sh line 35'
+ message='oe_test_swap_compress.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_swap_compress.sh line 35'
Sat Feb 15 14:13:39 2025 - ERROR - oe_test_swap_compress.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ swapon '/dev/openeuler*/swap'
swapon: cannot open /dev/openeuler*/swap: No such file or directory
++ free -lh
++ grep -i swap
++ awk '{print $2}'
++ awk -FG '{print $1}'
+ swap2=0B
++ echo '0B > 0B'
++ bc
+ '[' 0 -eq 1 ']'
+ CHECK_RESULT 1 0 0 'Compression failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Compression failed'
+ exit_mode=0
+ '[' -z '1 0 0 Compression failed' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Compression failed'
+ LOG_ERROR 'Compression failed'
+ message='Compression failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Compression failed'
Sat Feb 15 14:13:40 2025 - ERROR - Compression failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_swap_compress.sh line 39'
+ message='oe_test_swap_compress.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_swap_compress.sh line 39'
Sat Feb 15 14:13:40 2025 - ERROR - oe_test_swap_compress.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Feb 15 14:13:40 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Feb 15 14:13:41 2025 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the tet environment.'
+ message='Start to restore the tet environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the tet environment.'
Sat Feb 15 14:13:41 2025 - INFO  - Start to restore the tet environment.
+ swapoff /dev/dm-1
swapoff: /dev/dm-1: swapoff failed: No such file or directory
+ lvextend -L +1G -f '/dev/openeuler*/swap'
oe_test_swap_compress.sh: line 46: lvextend: command not found
+ mkswap '/dev/openeuler*/swap'
mkswap: cannot open /dev/openeuler*/swap: No such file or directory
+ swapon '/dev/openeuler*/swap'
swapon: cannot open /dev/openeuler*/swap: No such file or directory
+ LOG_INFO 'End to restore the tet environment.'
+ message='End to restore the tet environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the tet environment.'
Sat Feb 15 14:13:41 2025 - INFO  - End to restore the tet environment.
